name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install black
      run: pip install black
    - name: Check formatting
      run: black --check .
