name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unittest
      env:
        FDC_KEY: ${{ secrets.FDC_KEY }} 
      run: |
        python -m unittest discover -s ./tests -v
