name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with: 
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run unittest
      env:
        FDC_KEY: ${{ secrets.FDC_KEY }} 
      run: |
        python -m unittest discover -s ./tests -v

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '14', '12' ]
    name: Node ${{ matrix.node }} validation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: node version-check.js
      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm audit --audit-level=critical 